extends: airbnb-base
rules:
  class-methods-use-this:
    - error
    -
      exceptMethods:
        - closeStream
        - execute
        - executeCommand
        - executeShell
        - resizeTerm
  no-unused-vars:
    - warn
  no-shadow:
    - warn
  semi:
    - off
  padded-blocks:
    - off
  comma-dangle:
    - off
      