#!/usr/bin/env node
//
// Copyright (C) 2015 Lukasz Bacik <mail@luka.sh>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

const program = require('commander')
const fs = require('fs')
const Server = require('ssh2').Server
const pjson = require('./package.json')
const PassthroughFactory = require('./src/passthrough/factory')
const SshPassthroughListener = require('./src/ssh-server-listener.js')

const VERSION = pjson.version
const DEFAULT_PORT = 22
const DEFAULT_ADDRESS = '127.0.0.1'
const DEFAULT_SHELL = '/bin/sh'
const DEFAULT_TARGET = 'shell'
const DEFAULT_SERVER_KEY_FILE = 'server-key'

const DEFAULT_DOCKER_SOCKET = '/var/run/docker.sock'
const DEFAULT_DOCKER_SEPARATOR = '/'

program
  .version(VERSION)
  .option('--server-prv-key [path]', '', DEFAULT_SERVER_KEY_FILE)
  .option('-a, --address [ip]', '', DEFAULT_ADDRESS)
  .option('-p, --port [port]', '', DEFAULT_PORT)
  .option('--target [target]', '', DEFAULT_TARGET)
  .option('-s, --shell [shell]', '', DEFAULT_SHELL)
  .option('--docker-socket [socket]', '', DEFAULT_DOCKER_SOCKET)
  .option('--docker-separator [separator]', '', DEFAULT_DOCKER_SEPARATOR)
  .parse(process.argv)

const passthroughOptions = {
  target: program.target,
  shell: program.shell,
  version: VERSION,
  dockerSocket: program.dockerSocket,
  dockerSeparator: program.dockerSeparator,
}

const serverPrvKey = program.serverPrvKey
const serverPort = program.port
const serverAddress = program.address
let hostPrvKey

try {
  hostPrvKey = fs.readFileSync(serverPrvKey)
} catch (e) {
  console.log(e)
}

new Server({
  hostKeys: [hostPrvKey],
}, (client) => {
  const sshPassthroughListener =
      new SshPassthroughListener(passthroughOptions, PassthroughFactory)
  sshPassthroughListener.connectionRequest(client)
}).listen(serverPort, serverAddress, () => {
  console.log(`Listening on port ${serverAddress}:${serverPort}`)
})
